
on: [push]
name: deploy_branch

env:
  IMAGE_NAME: bdhwan/redash

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.22.1]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.npm
            ./node_modules
            ./packages/fumi-custom-module/node_modules
            ./packages/fumi-custom-module/*/node_modules
            ./packages/efluvi-admin-portal/node_modules
            ./packages/efluvi-api-server/node_modules
            ./packages/fumi-user-capacitor/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/npm-shrinkwrap.json') }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(TZ=Asia/Seoul date +'%Y%m%d_%H%M')"


      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.IMAGE_NAME}}
          tags: |
            type=raw,value=${{ steps.extract_branch.outputs.branch }}
            type=raw,value=${{ steps.extract_branch.outputs.branch }}_${{ steps.date.outputs.date }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}

      